[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6f4ab0377ed0bb3da4bb7df5a63194dab147a85"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "6244c383b080a6b0189929bb35ab7615a1a573c26fe144d47e99d7d710f29df4"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.7+0/blockSQP2.v0.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b736d8987905f1bf645aac420a58253998afc2b"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "369d8572be7708e4831f4ea099d4cdabf67f31bce3bd5a1e715721df29d86760"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.7+0/blockSQP2.v0.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
