[[blockSQP2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1acc0fed30daf540d904116b7e8f1ae3c97ed275"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "45ebddebd356b70e081a97c63ff8cf02a864ad24dfc4a9e4477c9de9493eb4eb"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.0+0/blockSQP2.v0.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1ed282a282be33fb2aa4eb5d3950bab1d1473ba"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "bdfaac424520401ec6e6e91c7fbc910dc5f617636e594b2a7115d5d392a15a45"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.0+0/blockSQP2.v0.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[blockSQP2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a97c2fed6618020525d2b7e4b84c1044fcee1865"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "34f0c684dece651897bc7e3f886e790bfb5c865113942968e6ed4e944f07e499"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.0+0/blockSQP2.v0.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[blockSQP2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95758b8aab515959652e5c7cee0a795f3708b323"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "155a047a3869bc974c34c54ef7c7bf6596ad00be58a9ff5dd4a30c158fd80c8b"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.0+0/blockSQP2.v0.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "148f2a87f36adfaf349fccabdf84352502cf8dea"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "afce0c1f41a377c60002f0a29bb10a14f34fac6b4c6adba809ce99ceef3ed9a4"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.0+0/blockSQP2.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5309500ea855250fe6714c581f7fa230047051c2"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "03b6a1ca68b65468057dc6e8c89ac65c6a968b2e7947936e9fb4620dd715b8f5"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.0+0/blockSQP2.v0.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
