[[blockSQP2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4435fa7846ae0780ff7e58385de03b0ed076a5e7"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "2b217c81e5aa03b26bf6173522daf3fc35216cc619608e3b643820fa7bcd2425"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.20+0/blockSQP2.v0.0.20.aarch64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cf7f160252c1f04c4812eb84d98a41cb541e7da"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "250bd724a526c61524032fe91662c23789c0281a52d52ed3148a873a6265a637"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.20+0/blockSQP2.v0.0.20.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[blockSQP2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7d7e3d4714783c17926b35d37081a057300b526"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "987b8a7e3cd1445e797eeeec43da0b0213b73075b242dc9b2778cfbd8e2cbf7e"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.20+0/blockSQP2.v0.0.20.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[blockSQP2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "039e192891fe75a41c790034cce38e51dca53803"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "07bb4210a2a73a2fcfd22b2811770888b8208c545c58225542d07aeeeae3deb8"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.20+0/blockSQP2.v0.0.20.powerpc64le-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bbf4e0d02302e3cb95943881ea2d331a281cebf"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "da3233e319bef9767ba54764e88bb1fed1e03895c92e63edfbb0d45b4e8dae84"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.20+0/blockSQP2.v0.0.20.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "345933710bde41c80e1c7720ef83664536c252b5"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "6deec55455d9dee3bc7d023435785d5cccd99a8d0503109be227841c2e06f9a3"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.20+0/blockSQP2.v0.0.20.x86_64-w64-mingw32-cxx11.tar.gz"
