[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02ea7aef4d79553617d248ba11eeeebd43f4766c"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "48565f621aa143e6c3329a033b1c42c755a113ee1ea26e375dac7210b55634d4"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.3+0/blockSQP2.v0.0.3.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7365820ac4040427a21244ee544945daa63c6943"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "1db4ea82e6478d2a8bbc4ce5417e9d1791a04b8287c067baa3b13d70ff55563d"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.3+0/blockSQP2.v0.0.3.x86_64-w64-mingw32-cxx11.tar.gz"
