[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b49ccfe54bdeb0cf384a11b4d4f5dc4a562a33e0"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "21fda80890ca9afa76d1b02b028b7bdd5a44ab4a6350c171428446e5e7d82986"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.2+0/blockSQP2.v0.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8a5fdb4f0dffabbd9b12b14d807fbbe8e27ea80"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "6c08942e7fa05fa9774aeb90c7160c27f63ffa7e7d0e5750ab6eaa50b3860365"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.2+0/blockSQP2.v0.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
