[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e6a3cf79540d14082b74e0991db342766f1a58f"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "6d7bb391491830d963692a34e7195fc92b490655c73519fc0f0c81dcb739b69a"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.10+0/blockSQP2.v0.0.10.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e8d8638ae9b7a30c82d900a19d013c15304d21d"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "b821c76d803d2f719e609dfef901e57aff591a2e60f2525e308df4d57553e1db"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.10+0/blockSQP2.v0.0.10.x86_64-w64-mingw32-cxx11.tar.gz"
