[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bbf4e0d02302e3cb95943881ea2d331a281cebf"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "da3233e319bef9767ba54764e88bb1fed1e03895c92e63edfbb0d45b4e8dae84"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.12+0/blockSQP2.v0.0.12.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "345933710bde41c80e1c7720ef83664536c252b5"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "6deec55455d9dee3bc7d023435785d5cccd99a8d0503109be227841c2e06f9a3"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.12+0/blockSQP2.v0.0.12.x86_64-w64-mingw32-cxx11.tar.gz"
