[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac6f5ad900a2b1386a55c0ece9902c7b06f95a2e"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "1898df735bb8bda1e404fba47f859b40eed0e4601aafc17d3488d4769e0a2d07"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.9+0/blockSQP2.v0.0.9.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a23fd9f6179b42331186dbbde0656897bf880f1"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "f80537cb214dc074a90945a15adf806d1884f8bdc6e00f7f6a208d15638be7fb"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.9+0/blockSQP2.v0.0.9.x86_64-w64-mingw32-cxx11.tar.gz"
