[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6f4ab0377ed0bb3da4bb7df5a63194dab147a85"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "6244c383b080a6b0189929bb35ab7615a1a573c26fe144d47e99d7d710f29df4"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.8+0/blockSQP2.v0.0.8.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b6e8ffe910d44d6c39e8801de96cde29efff28e"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "1ecb4b02b5de8a2944839f7c7fbb00d564fd8f340f5c70a8a31584e7503534b4"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.8+0/blockSQP2.v0.0.8.x86_64-w64-mingw32-cxx11.tar.gz"
