[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e6a3cf79540d14082b74e0991db342766f1a58f"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "6d7bb391491830d963692a34e7195fc92b490655c73519fc0f0c81dcb739b69a"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.11+0/blockSQP2.v0.0.11.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6c248687c30df16a9cdff515847639212006ebf"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "e55eab70d5b4636f8ed02ae0b22b18dc77f773a455bd8243adc8524c596112ca"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.0.11+0/blockSQP2.v0.0.11.x86_64-w64-mingw32-cxx11.tar.gz"
