name = "blockSQP2_jll"
uuid = "8a1cb406-4d92-5272-b91c-0b6599bad0b1"
version = "0.0.2+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
OpenBLAS_jll = "4536629a-c528-5b80-bd46-f80d51c5b363"
qpOASES_jll = "f16e1b62-db32-537f-94d1-ea38eaaf9298"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.11"
OpenBLAS_jll = "0.3.23"
qpOASES_jll = "3.2.2"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
