name = "blockSQP2_jll"
uuid = "8a1cb406-4d92-5272-b91c-0b6599bad0b1"
version = "0.1.0+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
MUMPS_seq_jll = "d7ed1dd3-d0ae-5e8e-bfb4-87a502085b8d"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.9"
MUMPS_seq_jll = "500.800.200"
Libdl = "< 0.0.1, 1"
OpenBLAS32_jll = "0.3.30"
Artifacts = "< 0.0.1, 1"
